name: 'Branch name'

on: create

jobs:
    hello:
        if: ${{ github.ref_type }} == 'branch' && 
        runs-on: ubuntu-latest
        steps:
            - name: Check branch name
              if: ${{!startsWith(github.ref_name, 'dependabot')}}
              run: |
                if ! [[ ${{ github.ref_name }} =~ ^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)\/v(2|3)-[a-zA-Z0-9\-]{1,50}$ ]]; then
                  echo "Published branch '${{ github.ref_name }}' doesn't follow the naming standards of this repository."
                  echo "Please consider switching to a new branch respecing these." 
                  echo "See 'CONTRIBUTING.md' for details."
                  exit 1
                fi
