name: Create not latest release

on:
  push:
    branches:
      - 'main'

env:
  NEW_TAG: "v4.1.14"
  RELEASE_NOTE_EXCLUDED_TYPES: docs,style,chore,other

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      previous-tag: ${{ steps.previousTag.outputs.previousTag }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Get previous v2 release tag
        id: previousTag
        run: echo "previousTag=$(git --no-pager tag --sort=creatordate --merged ${{ github.ref_name }} | grep "^v[0-9]\+\.[0-9]\+\.[0-9]\+$" | tail -1)" >> $GITHUB_OUTPUT

      - name: Create tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{env.NEW_TAG}}

      - name: Create release note
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          fromTag: ${{env.NEW_TAG}}
          toTag:  ${{ steps.previousTag.outputs.previousTag }}
          excludeTypes: ${{ env.RELEASE_NOTE_EXCLUDED_TYPES }}
          token: ${{ secrets.GITHUB_TOKEN }}
          writeToFile: false

      - uses: ncipollo/release-action@v1
        with:
          tag: ${{env.NEW_TAG}}
          commit: ${{ github.head_ref || github.ref }}
          name: ${{env.NEW_TAG}}
          body: ${{steps.changelog.outputs.changes}}
          #makeLatest: 'false'

  commit-changelog:
    needs: create-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      # doint this twice but meh
      - name: Create release note
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          fromTag: ${{ env.NEW_TAG }}
          toTag:  ${{ needs.create-release.outputs.previous-tag }}
          excludeTypes: ${{ env.RELEASE_NOTE_EXCLUDED_TYPES }}
          token: ${{ secrets.GITHUB_TOKEN }}
          writeToFile: true
          changelogFilePath: 'CHANGELOG.md'

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: 'docs(changelog): ${{env.NEW_TAG}} update [skip ci]'
          file_pattern: CHANGELOG.md
