name: Create not latest release

on:
  push:
    branches:
      - 'main'

env:
  NEW_TAG: "v4.1.6"

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Get previous v2 release tag
        id: previousTag
        run: echo "previousTag=$(git --no-pager tag --sort=creatordate --merged ${{ github.ref_name }} | grep "^v[0-9]\+\.[0-9]\+\.[0-9]\+$" | tail -1)" >> $GITHUB_OUTPUT

      - name: Create release note
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          fromTag: ${{ github.sha }}
          toTag:  ${{ steps.previousTag.outputs.previousTag }}
          excludeTypes: style,chore,other
          token: ${{ secrets.GITHUB_TOKEN }}
          writeToFile: true
          changelogFilePath: CHANGELOG.md

      - uses: ncipollo/release-action@v1
        with:
          tag: ${{env.NEW_TAG}}
          commit: ${{ github.head_ref || github.ref }}
          name: ${{env.NEW_TAG}}
          body: ${{steps.changelog.outputs.changes}}
          makeLatest: 'false'

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: 'docs(changelog): ${{env.NEW_TAG}} update [skip ci]'
          file_pattern: CHANGELOG.md
