name: PR with skip

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  test: 
    if: (${{ ! contains(github.event.pull_request.labels.*.name, 'deploy-snapshot') }}) && (${{ github.event.pull_request.draft }} == false)
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
