name: PR with skip

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  test: 
    if: github.event.pull_request.draft == false # && ${{ ! contains(github.event.pull_request.labels.*.name, 'foo-label') }}
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
