name: 'Push on PR on main'

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:

  hello:
    runs-on: ubuntu-latest
    steps:
      - name: 'Say hello'
        run: echo hello
