name: Release note

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create release note
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          fromTag: 'v3.2.2'
          toTag: 'v1.0.0'
          token: ${{ secrets.GITHUB_TOKEN }}
          writeToFile: true
          excludeTypes: docs,other,style