name: test current hash

on:
  pull_request:

jobs:
  single-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          git rev-parse --short HEAD

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - run: |
          git rev-parse --short HEAD
